cache: bundler
sudo: false
rvm:
  - 2.1.9
  - 2.2.5
  - 2.3.1
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.0.gemfile
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile
bundler_args: --no-deployment
script: "bundle exec rake test"
matrix:
  exclude:
    - rvm: 2.1.9
      gemfile: gemfiles/rails5.0.gemfile
branches:
  only: master
