cache: bundler
sudo: false
before_install:
  - gem update --system
  - gem install bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile
  - gemfiles/rails5.1.gemfile
  - gemfiles/rails5.2.gemfile
bundler_args: --no-deployment
script: "bundle exec rake test"
branches:
  only: master
