version: 2.1

jobs:
  rake-test:
    parameters:
      ruby-version:
        type: string
      gemfile:
        type: string
    docker:
      - image: circleci/ruby:<< parameters.ruby-version >>
      - image: circleci/mysql:5.7
    environment:
      BUNDLE_GEMFILE: << parameters.gemfile >>
    steps:
      - checkout
      - run: sudo apt install -y mysql-client
      - run: bundle install
      - run: bundle exec rake test

workflows:
  version: 2
  build:
    jobs:

      - rake-test:
          name: "ruby2.3 rails4.2"
          ruby-version: "2.3"
          gemfile: "gemfiles/rails4.2.gemfile"
      - rake-test:
          name: "ruby2.3 rails5.0"
          ruby-version: "2.3"
          gemfile: "gemfiles/rails5.0.gemfile"
      - rake-test:
          name: "ruby2.3 rails5.1"
          ruby-version: "2.3"
          gemfile: "gemfiles/rails5.1.gemfile"
      - rake-test:
          name: "ruby2.3 rails5.2"
          ruby-version: "2.3"
          gemfile: "gemfiles/rails5.2.gemfile"
      - rake-test:
          name: "ruby2.4 rails4.2"
          ruby-version: "2.4"
          gemfile: "gemfiles/rails4.2.gemfile"
      - rake-test:
          name: "ruby2.4 rails5.0"
          ruby-version: "2.4"
          gemfile: "gemfiles/rails5.0.gemfile"
      - rake-test:
          name: "ruby2.4 rails5.1"
          ruby-version: "2.4"
          gemfile: "gemfiles/rails5.1.gemfile"
      - rake-test:
          name: "ruby2.4 rails5.2"
          ruby-version: "2.4"
          gemfile: "gemfiles/rails5.2.gemfile"
      - rake-test:
          name: "ruby2.5 rails4.2"
          ruby-version: "2.5"
          gemfile: "gemfiles/rails4.2.gemfile"
      - rake-test:
          name: "ruby2.5 rails5.0"
          ruby-version: "2.5"
          gemfile: "gemfiles/rails5.0.gemfile"
      - rake-test:
          name: "ruby2.5 rails5.1"
          ruby-version: "2.5"
          gemfile: "gemfiles/rails5.1.gemfile"
      - rake-test:
          name: "ruby2.5 rails5.2"
          ruby-version: "2.5"
          gemfile: "gemfiles/rails5.2.gemfile"
